# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

from flask import Flask, jsonify, request
import pandas as pd

from logging_config import get_logger
from model import validate_inputs, load_model
from baseline import SeasonalNaiveBaseline
from monitoring import input_drift_flags
import os
import pandas as pd

app = Flask(__name__)
logger = get_logger("api")

# Load model at startup
REVENUE_MODEL = None
BASELINE = None

def _load_history_for_baseline() -> pd.DataFrame:
    path = os.getenv("HISTORY_CSV", "")
    if path and os.path.exists(path):
        df = pd.read_csv(path)
        return df
    # fallback empty; baseline will return 0 or mean
    return pd.DataFrame(columns=["date", "country", "revenue"])

@app.before_first_request
def init() -> None:
    global REVENUE_MODEL, BASELINE
    REVENUE_MODEL = load_model()
    BASELINE = SeasonalNaiveBaseline(history=_load_history_for_baseline())

@app.get("/health")
def health():
    return jsonify({"status": "ok"})

@app.post("/predict")
def predict():
    try:
        payload = request.get_json(force=True, silent=False)
        country, target_date = validate_inputs(payload)

        pred = REVENUE_MODEL.predict_one(country, target_date)
        base = BASELINE.predict(country, target_date)

        drift = input_drift_flags(country, target_date)

        logger.info(
            "prediction",
            extra={
                "extra": {
                    "country": country,
                    "date": str(target_date.date()),
                    "prediction": pred,
                    "baseline": base,
                    "drift": drift,
                }
            },
        )

        return jsonify(
            {
                "country": country,
                "date": str(target_date.date()),
                "prediction": pred,
                "baseline_prediction": base,
                "drift": drift,
            }
        )
    except Exception as e:
        logger.info("bad_request", extra={"extra": {"error": str(e)}})
        return jsonify({"error": str(e)}), 400

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)