# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

from dataclasses import dataclass
import pandas as pd

@dataclass
class SeasonalNaiveBaseline:
    """
    Predicts using revenue from the same month one year earlier if available,
    else uses mean revenue for that country.
    """
    history: pd.DataFrame  # columns: [date, country, revenue]

    def predict(self, country: str, target_date: pd.Timestamp) -> float:
        df = self.history.copy()
        df["date"] = pd.to_datetime(df["date"])
        if country != "ALL":
            df = df[df["country"] == country]

        # Same month last year
        last_year = target_date - pd.DateOffset(years=1)
        match = df[df["date"] == last_year]
        if len(match) > 0:
            return float(match["revenue"].iloc[-1])

        # Fallback mean
        if len(df) == 0:
            return 0.0
        return float(df["revenue"].mean())