# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import os
from dataclasses import dataclass

@dataclass(frozen=True)
class Settings:
    # Isolation: tests can override ARTIFACT_DIR and LOG_DIR
    ARTIFACT_DIR: str = os.getenv("ARTIFACT_DIR", "./artifacts")
    LOG_DIR: str = os.getenv("LOG_DIR", "./logs")
    ENV: str = os.getenv("ENV", "prod")  # "test" in unit tests
    MODEL_FILE: str = os.getenv("MODEL_FILE", "model.joblib")
    TRAIN_STATS_FILE: str = os.getenv("TRAIN_STATS_FILE", "train_stats.json")

settings = Settings()