# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import os
import pandas as pd

def ingest_raw_csv(raw_path: str, output_path: str) -> pd.DataFrame:
    """
    Reads raw data and writes a cleaned CSV suitable for training.
    Expected columns in raw: date, country, revenue
    """
    df = pd.read_csv(raw_path)
    required = {"date", "country", "revenue"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in raw data: {sorted(list(missing))}")

    df["date"] = pd.to_datetime(df["date"]).dt.to_period("M").dt.to_timestamp()
    df["country"] = df["country"].astype(str)
    df["revenue"] = pd.to_numeric(df["revenue"], errors="coerce").fillna(0.0)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    df.to_csv(output_path, index=False)
    return df

if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--raw", required=True, help="Path to raw CSV")
    p.add_argument("--out", required=True, help="Path to write cleaned CSV")
    args = p.parse_args()

    ingest_raw_csv(args.raw, args.out)
    print(f"Wrote cleaned data to {args.out}")