# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from config import settings

def ensure_dirs() -> None:
    os.makedirs(settings.LOG_DIR, exist_ok=True)

class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload: Dict[str, Any] = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "msg": record.getMessage(),
        }
        # Allow structured extras
        if hasattr(record, "extra") and isinstance(record.extra, dict):
            payload.update(record.extra)
        return json.dumps(payload, ensure_ascii=False)

def get_logger(name: str = "app", log_file: Optional[str] = None) -> logging.Logger:
    ensure_dirs()
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)
    logger.propagate = False

    # Avoid duplicate handlers if imported multiple times
    if logger.handlers:
        return logger

    formatter = JsonFormatter()

    if log_file is None:
        log_file = os.path.join(settings.LOG_DIR, f"{name}.log")

    fh = logging.FileHandler(log_file)
    fh.setFormatter(formatter)
    logger.addHandler(fh)

    sh = logging.StreamHandler()
    sh.setFormatter(formatter)
    logger.addHandler(sh)

    return logger