# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

from typing import Dict, Optional
import math
import pandas as pd
from model import load_train_stats

def z_score(x: float, mean: float, std: float) -> float:
    std = std if std and std > 0 else 1.0
    return (x - mean) / std

def input_drift_flags(country: str, target_date: pd.Timestamp) -> Dict[str, object]:
    stats: Optional[dict] = load_train_stats()
    if not stats:
        return {"drift_check_available": False}

    m = float(target_date.month)
    y = float(target_date.year)

    mz = z_score(m, stats["month_mean"], stats["month_std"])
    yz = z_score(y, stats["year_mean"], stats["year_std"])

    unknown_country = (country != "ALL") and (country not in stats.get("countries", []))

    # Simple thresholding
    flags = {
        "drift_check_available": True,
        "month_z": mz,
        "year_z": yz,
        "month_drift": bool(abs(mz) > 3.0),
        "year_drift": bool(abs(yz) > 3.0),
        "unknown_country": bool(unknown_country),
        "any_alert": bool(abs(mz) > 3.0 or abs(yz) > 3.0 or unknown_country),
    }
    return flags


def compute_mape(y_true: float, y_pred: float) -> float:
    denom = y_true if abs(y_true) > 1e-9 else 1.0
    return float(abs(y_true - y_pred) / denom)