# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import os
import numpy as np
import pandas as pd

from config import settings
from model import train, save_model, load_model
from baseline import SeasonalNaiveBaseline

def make_synthetic_data() -> pd.DataFrame:
    # Synthetic monthly revenue by country with seasonality
    rng = np.random.default_rng(7)
    dates = pd.date_range("2022-01-01", "2024-12-01", freq="MS")
    countries = ["US", "CA", "GB", "FR"]

    rows = []
    for c in countries:
        base = {"US": 1200, "CA": 700, "GB": 900, "FR": 800}[c]
        for d in dates:
            season = 150 * np.sin(2 * np.pi * d.month / 12.0)
            trend = (d.year - 2022) * 40
            noise = rng.normal(0, 60)
            rev = max(base + season + trend + noise, 0)
            rows.append({"date": d, "country": c, "revenue": float(rev)})
    return pd.DataFrame(rows)

def train_and_compare(df: pd.DataFrame) -> dict:
    # Simple holdout: last 6 months per country
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])
    cutoff = df["date"].max() - pd.DateOffset(months=6)
    train_df = df[df["date"] <= cutoff]
    test_df = df[df["date"] > cutoff]

    rm = train(train_df)
    baseline = SeasonalNaiveBaseline(history=train_df)

    # Evaluate MAPE
    mape_model = []
    mape_base = []
    for _, r in test_df.iterrows():
        y_true = float(r["revenue"])
        y_pred_model = rm.predict_one(r["country"], r["date"])
        y_pred_base = baseline.predict(r["country"], r["date"])
        denom = y_true if abs(y_true) > 1e-9 else 1.0
        mape_model.append(abs(y_true - y_pred_model) / denom)
        mape_base.append(abs(y_true - y_pred_base) / denom)

    results = {
        "mape_model": float(np.mean(mape_model)),
        "mape_baseline": float(np.mean(mape_base)),
        "better_than_baseline": bool(np.mean(mape_model) < np.mean(mape_base)),
        "train_rows": int(len(train_df)),
        "test_rows": int(len(test_df)),
    }
    return rm, results

if __name__ == "__main__":
    data_path = os.getenv("TRAIN_DATA", "")
    if data_path and os.path.exists(data_path):
        df = pd.read_csv(data_path)
    else:
        df = make_synthetic_data()

    rm, results = train_and_compare(df)
    save_model(rm)

    os.makedirs(settings.ARTIFACT_DIR, exist_ok=True)
    with open(os.path.join(settings.ARTIFACT_DIR, "model_comparison.txt"), "w", encoding="utf-8") as f:
        for k, v in results.items():
            f.write(f"{k}: {v}\n")

    print("Training complete.")
    print(results)
    print(f"Saved model to {os.path.join(settings.ARTIFACT_DIR, settings.MODEL_FILE)}")