# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import pytest
import pandas as pd

def test_validate_inputs_ok():
    from model import validate_inputs
    c, d = validate_inputs({"country": "US", "date": "2025-02-01"})
    assert c == "US"
    assert isinstance(d, pd.Timestamp)

def test_validate_inputs_all_aliases():
    from model import validate_inputs
    c, _ = validate_inputs({"country": "global", "date": "2025-02-01"})
    assert c == "ALL"

def test_train_and_predict():
    import train
    df = train.make_synthetic_data()
    rm, results = train.train_and_compare(df)
    y = rm.predict_one("US", pd.to_datetime("2025-01-01"))
    assert isinstance(y, float)
    assert y >= 0.0
    assert "mape_model" in results