# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import os
import json
import pytest
import pandas as pd

@pytest.fixture(autouse=True)
def isolate_artifacts(tmp_path, monkeypatch):
    monkeypatch.setenv("ENV", "test")
    monkeypatch.setenv("ARTIFACT_DIR", str(tmp_path / "artifacts_test"))
    monkeypatch.setenv("LOG_DIR", str(tmp_path / "logs_test"))
    yield

def test_health_endpoint():
    # Train a model first
    import train
    df = train.make_synthetic_data()
    rm, _ = train.train_and_compare(df)
    from model import save_model
    save_model(rm)

    from app import app
    client = app.test_client()

    resp = client.get("/health")
    assert resp.status_code == 200
    assert resp.get_json()["status"] == "ok"

def test_predict_country_and_all():
    import train
    df = train.make_synthetic_data()
    rm, _ = train.train_and_compare(df)
    from model import save_model
    save_model(rm)

    from app import app
    client = app.test_client()

    # specific country
    resp = client.post("/predict", json={"country": "US", "date": "2025-01-01"})
    assert resp.status_code == 200
    j = resp.get_json()
    assert j["country"] == "US"
    assert "prediction" in j

    # all countries combined
    resp2 = client.post("/predict", json={"country": "ALL", "date": "2025-01-01"})
    assert resp2.status_code == 200
    j2 = resp2.get_json()
    assert j2["country"] == "ALL"
    assert "prediction" in j2

def test_predict_bad_input():
    import train
    df = train.make_synthetic_data()
    rm, _ = train.train_and_compare(df)
    from model import save_model
    save_model(rm)

    from app import app
    client = app.test_client()

    resp = client.post("/predict", json={"country": "US"})
    assert resp.status_code == 400
    assert "Missing required field" in resp.get_json()["error"]