# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRDBrvASMREc5zMkNiOzQBfqIdf-LseK
"""

import os
import json

def test_logging_writes_json(tmp_path, monkeypatch):
    monkeypatch.setenv("ENV", "test")
    monkeypatch.setenv("LOG_DIR", str(tmp_path))

    from logging_config import get_logger

    log_path = os.path.join(str(tmp_path), "x.log")
    logger = get_logger("x", log_file=log_path)

    logger.info("hello", extra={"extra": {"country": "US", "prediction": 123.4}})

    assert os.path.exists(log_path)
    with open(log_path, "r", encoding="utf-8") as f:
        line = f.readline().strip()
    obj = json.loads(line)
    assert obj["msg"] == "hello"
    assert obj["country"] == "US"
    assert obj["prediction"] == 123.4